name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout código
      uses: actions/checkout@v2

    - name: Configurar Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14' # Ajusta la versión de Node.js según tus necesidades

    - name: Instalar dependencias
      run: npm install

    - name: Construir sitio
      run: npm run build # Asegúrate de que este comando genere los archivos para GitHub Pages en la carpeta correcta (por lo general, 'dist' o 'build')

    - name: Publicar en GitHub Pages
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: dist # Carpeta que contiene los archivos para publicar
        commit_message: "Auto-deployed by GitHub Actions"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
